apiVersion: apps/v1
kind: Deployment
metadata:
  name: applet-deployment
  labels:
    app: applet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: applet
  template:
    metadata:
      labels:
        app: applet
    spec:
      containers:
      - name: applet-container
        image: todo:latest
        ports:
        - containerPort: 80
