apiVersion: v1
kind: Pod
metadata:
  name: applet-pod-init
  labels:
    app: applet
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ['sh', '-c', 'echo "Init container running!"; sleep 3600']
  containers:
  - name: applet-container
    image: todo:latest 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
