apiVersion: v1
kind: Pod
metadata:
  name: applet-pod
  labels:
    app: applet
spec:
  containers:
  - name: applet-container
    image: todo:latest 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
