apiVersion: v1
kind: ReplicationController
metadata:
  name: applet-replicas
  labels:
      app: applet
spec:
  replicas: 3
  selector:
    app: applet
  template:
    metadata:
      labels:
        app: applet
    spec:
      containers:
      - name: applet-container
        image: todo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
